name: "Checkout"
description: "Checkout repository with cache"
runs:
  using: composite
  steps:
    - name: Cache cloned repo
      id: repo_cache
      uses: wikibusiness/local-cache@v5
      with:
        path: /home/runner/_work/platforms-cached
        base: /home/runner/cache
        key: repo-${{ github.repository }}-v1
        clean-key: repo

    - name: Determine correct commit SHA
      id: get_sha
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"
        else
          echo "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Sync repository (clone or pull)
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -e
        SHA=${{ steps.get_sha.outputs.sha }}
        REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}"

        if [ ! -d /home/runner/_work/platforms-cached/.git ]; then
          echo "Cloning fresh repo..."
          git clone "$REPO_URL" /home/runner/_work/platforms-cached --no-checkout
          echo "Done cloning."
        fi

        cd /home/runner/_work/platforms-cached

        echo "Fetching commit..."
        git fetch --depth=1 origin "$SHA"

        echo "Checking out correct commit..."
        git checkout "$SHA"

    - name: Copy repo into workspace
      shell: bash
      run: |
        rsync -a --delete /home/runner/_work/platforms-cached/ "${{ github.workspace }}/"
