name: "Checkout"
description: "Checkout repository with cache"
runs:
  using: composite
  steps:
    - name: Cache cloned repo
      id: repo_cache
      uses: wikibusiness/local-cache@v5
      with:
        path: /home/runner/_work/platforms-cached
        base: /home/runner/cache
        key: repo-${{ github.repository }}-v1
        clean-key: repo

    # - name: Determine correct commit SHA
    #   id: get_sha
    #   run: |
    #     if [[ "${{ github.event_name }}" == "pull_request" ]]; then
    #       echo "sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"
    #     else
    #       echo "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"
    #     fi

    - name: Sync repository (clone or pull)
      shell: bash
      run: |
        set -e

        # Use token-based URL for private access
        REPO_URL="https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}"

        if [ ! -d /home/runner/_work/platforms-cached/.git ]; then
          echo "Cloning fresh repo..."
          git clone "$REPO_URL" /home/runner/_work/platforms-cached
          echo "Done cloning."
        fi

        cd /home/runner/_work/platforms-cached

        echo "Fetching latest..."
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          git fetch origin "pull/${{ github.event.pull_request.number }}/merge"
          git checkout FETCH_HEAD
        else
          git fetch origin
          git checkout ${{ github.sha }}
        fi

    - name: Copy repo into workspace
      shell: bash
      run: |
        rsync -a --delete /home/runner/_work/platforms-cached/ "${{ github.workspace }}/"
